services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    container_name: telescope-frontend

  constellations-api:
    build:
      context: ../../constellations-api
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      USE_MOCKS: 0

      CODEX_ADDRESS: "http://192.168.178.171:8081"
      PRIVATE_KEY: "0x821f73df2d38ac506e9735306766be701afcec7def45f7bfa184b6fd4e96185d"

