services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    container_name: telescope-frontend
  constellations-api:
    image: constellations-api
    build:
      context: ../../constellations-api
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    container_name: constellations-api
